export const characters = [
  {
    id: "vera",
    name: "Vera the Vector",
    animal: "Red Panda",
    concept: "Vectors & Direction",
    tagline: "Discover direction and magnitude",
    image: "/lovable-uploads/187f4ef7-dd45-4280-8f5d-626062d22c43.png",
    fullName: "Vera the Vector",
    catchphrase: "Direction and strength—that's my whole personality!",
    avatar: "/lovable-uploads/187f4ef7-dd45-4280-8f5d-626062d22c43.png",
    color: "from-red-600 to-orange-600",
    expertise: "Vectors & Vector Spaces",
    description: "Cheerful and adventurous explorer, equipped with a compass and a small backpack. Vera thinks in multiple dimensions and helps you navigate the world of vectors, matrices, and linear transformations with confidence and enthusiasm.",
    modules: ["Module 1: Vectors & Vector Spaces"]
  },
  {
    id: "max",
    name: "Matrix Max",
    animal: "Owl",
    concept: "Matrices & Structure",
    tagline: "Master structure and transformations",
    image: "/lovable-uploads/c18b892c-e964-45c1-9958-ae19c36dd3e7.png",
    fullName: "Matrix Max",
    catchphrase: "I organize worlds—row by row, column by column!",
    avatar: "/lovable-uploads/c18b892c-e964-45c1-9958-ae19c36dd3e7.png",
    color: "from-blue-600 to-indigo-600",
    expertise: "Matrices & Linear Mappings",
    description: "Energetic mathematician with hints of architectural elements; wears grid-patterned clothing, sports a calculator watch. Max helps you understand how matrices organize and transform mathematical worlds.",
    modules: ["Module 2: Matrices & Linear Mappings"]
  },
  {
    id: "eileen",
    name: "Eileen Eigen",
    animal: "Cat",
    concept: "Eigenvalues & Patterns",
    tagline: "Uncover hidden patterns",
    image: "/lovable-uploads/cd4be045-5470-40af-8be9-d32ee3e9258a.png",
    fullName: "Eileen Eigen",
    catchphrase: "Discovering hidden directions—that's the Eileen Eigen way!",
    avatar: "/lovable-uploads/cd4be045-5470-40af-8be9-d32ee3e9258a.png",
    color: "from-purple-600 to-pink-600",
    expertise: "Eigenvalues & Eigenvectors",
    description: "Quirky detective-explorer hybrid, characterized by a detective hat and exploration gear in purple and deep blue hues. Eileen uncovers hidden directions in data and transformations.",
    modules: ["Module 3: Eigenvalues & Eigenvectors"]
  },
  {
    id: "delta",
    name: "Dr. Delta",
    animal: "Hedgehog",
    concept: "Calculus & Change",
    tagline: "Understand change and rates",
    image: "/lovable-uploads/8ce908b7-0c65-464e-9eea-35e40714b0cd.png",
    fullName: "Dr. Delta",
    catchphrase: "Calculus is just watching how fast things change—and nobody does it better than Dr. Delta!",
    avatar: "/lovable-uploads/8ce908b7-0c65-464e-9eea-35e40714b0cd.png",
    color: "from-green-600 to-emerald-600",
    expertise: "Multivariate Calculus",
    description: "Thoughtful, precise scientist with subtle engineering elements; dressed in a lab coat, wears glasses, carries a clipboard. Dr. Delta clarifies concepts of derivatives, partial derivatives, and gradients.",
    modules: ["Module 4: Multivariate Calculus Foundations"]
  },
  {
    id: "greta",
    name: "Gradient Greta",
    animal: "Mountain Goat",
    concept: "Optimization",
    tagline: "Climb to optimal solutions",
    image: "/lovable-uploads/e942438f-5319-4038-a87a-81ec3cb17c87.png",
    fullName: "Gradient Greta",
    catchphrase: "Climb with me step by step—we'll find the lowest point together!",
    avatar: "/lovable-uploads/e942438f-5319-4038-a87a-81ec3cb17c87.png",
    color: "from-orange-600 to-red-600",
    expertise: "Optimization & Gradient Descent",
    description: "Determined climber and hiker, equipped with hiking gear, ropes, and earthy, natural-colored clothing. Greta teaches optimization through relatable analogies of climbing towards optimal solutions.",
    modules: ["Module 5: Optimization & Gradient Descent"]
  },
  {
    id: "pippa",
    name: "Probability Pippa",
    animal: "Rabbit",
    concept: "Probability & Chance",
    tagline: "Navigate uncertainty with magic",
    image: "/lovable-uploads/05977652-4008-4b5b-aa0d-f95ce287d3c8.png",
    fullName: "Probability Pippa",
    catchphrase: "Magic or math? Probability Pippa knows it's both!",
    avatar: "/lovable-uploads/05977652-4008-4b5b-aa0d-f95ce287d3c8.png",
    color: "from-pink-600 to-rose-600",
    expertise: "Probability & Distributions",
    description: "Quirky magician in playful, whimsical attire, featuring a magician's hat, wand, and costumes in rich purples and golds. Pippa explains probability using playful magic metaphors.",
    modules: ["Module 6: Probability & Distributions"]
  },
  {
    id: "bayes",
    name: "Bayes the Fox",
    animal: "Fox",
    concept: "Bayesian Inference",
    tagline: "Make smart inferences",
    image: "/lovable-uploads/ae438bc6-bcec-4fc5-a53f-53ee53055ba8.png",
    fullName: "Bayes the Fox",
    catchphrase: "When you're uncertain, follow Bayes the Fox to sniff out the truth!",
    avatar: "/lovable-uploads/ae438bc6-bcec-4fc5-a53f-53ee53055ba8.png",
    color: "from-indigo-600 to-purple-600",
    expertise: "Bayesian Inference",
    description: "Clever detective fox character, characterized by a detective's hat and magnifying glass, using warm orange and earthy tones. Bayes introduces Bayesian inference through detective narratives.",
    modules: ["Module 8: Bayesian Inference"]
  },
  {
    id: "sigmund",
    name: "Sigmund the Swan",
    animal: "Swan",
    concept: "Hypothesis Testing",
    tagline: "Test hypotheses elegantly",
    image: "/lovable-uploads/86febada-e78e-48ec-9d4b-015896eac929.png",
    fullName: "Sigmund the Swan",
    catchphrase: "One black swan can change everything—Sigmund helps you understand why!",
    avatar: "/lovable-uploads/86febada-e78e-48ec-9d4b-015896eac929.png",
    color: "from-teal-600 to-cyan-600",
    expertise: "Hypothesis Testing & Inference",
    description: "Elegant black swan with simple, iconic imagery, presented in clean black-and-white contrast. Sigmund teaches hypothesis testing using the powerful black swan metaphor.",
    modules: ["Module 7: Hypothesis Testing & Inference"]
  },
  {
    id: "sage",
    name: "Sage the Synthesis Owl",
    animal: "Owl",
    concept: "Capstone Synthesis",
    tagline: "Turn insight into impact",
    image: "/lovable-uploads/f1feea0f-0da6-45f5-a1aa-e0e8b5deab65.png",
    fullName: "Sage the Synthesis Owl",
    catchphrase: "Turning insight into impact—that's the Sage way!",
    avatar: "/lovable-uploads/f1feea0f-0da6-45f5-a1aa-e0e8b5deab65.png",
    color: "from-slate-600 to-gray-600",
    expertise: "Capstone Project",
    description: "Wise and thoughtful owl character who guides students through synthesizing all their learning into practical applications. Sage helps bring together knowledge from all previous modules.",
    modules: ["Module 9: Capstone Project"]
  }
]; 